apiVersion: v1
kind: Service
metadata:
  name: nginx-lb # service name
  labels:
    purpose: nginx-lb-demo     
spec:
  type: LoadBalancer
  selector:
    purpose: ds-demo
    project: roboshop 
    environment: dev
    app: nginx       
  ports: 
  - name: http
    protocol:  TCP
    port: 80 # service port
    targetPort: {{ .Values.service.targetPort }} # container port
